In [1]:
import pandas as pd

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive/')
# from google.colab import drive
# drive.flush_and_unmount()

In [ ]:
df = pd.read_csv('/Parking_Violations_Issued_-_Fiscal_Year_2022.csv')
df.shape

In [3]:
df = pd.read_csv(r'C:\Program Files\MongoDB\Server\5.0\bin\Parking_Violations_Issued_-_Fiscal_Year_2022.csv')
df.shape

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6312\3884526313.py:1: DtypeWarning: Columns (0,9,17,18,20,22,23,29,30,31,32,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Program Files\MongoDB\Server\5.0\bin\Parking_Violations_Issued_-_Fiscal_Year_2022.csv')

(644585, 43)

In [5]:
df.head(2)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1457617912,JEB5683,NY,PAS,06/25/2021,40.0,VAN,FORD,P,63430,...,GY,0.0,2007.0,-,3.0,NaN,NaN,NaN,NaN,NaN
1,1457617924,JAN2986,NY,PAS,06/25/2021,20.0,SUBN,DODGE,P,13490,...,BLU,0.0,2007.0,-,0.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.isna().sum()

Summons Number                            0
Plate ID                                 10
Registration State                        4
Plate Type                                4
Issue Date                                4
Violation Code                            4
Vehicle Body Type                      2355
Vehicle Make                            751
Issuing Agency                            4
Street Code1                              4
Street Code2                              5
Street Code3                              5
Vehicle Expiration Date                   5
Violation Location                   358495
Violation Precinct                        5
Issuer Precinct                           5
Issuer Code                               5
Issuer Command                       358228
Issuer Squad                         381960
Violation Time                           15
Time First Observed                  605088
Violation County                       1793
Violation In Front Of Or Opposite    362206
House Number                         364645
Street Name                              62
Intersecting Street                  253089
Date First Observed                       5
Law Section                               5
Sub Division                             92
Violation Legal Code                 286361
Days Parking In Effect               365117
From Hours In Effect                 475220
To Hours In Effect                   475221
Vehicle Color                         73447
Unregistered Vehicle?                627058
Vehicle Year                              5
Meter Number                         576875
Feet From Curb                            5
Violation Post Code                  399486
Violation Description                 17551
No Standing or Stopping Violation    644585
Hydrant Violation                    644585
Double Parking Violation             644585
dtype: int64

In [6]:
df[df['Issue Date'].isna()]

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
644581,"""error"" : true",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644582,"""message"" : ""Internal error""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644583,"""status"" : 500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644584,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 1) Find the number of tickets raised for the year 2022

In [11]:
df['Issue_Year'] = pd.to_datetime(df['Issue Date']).dt.year
df[df['Issue_Year']==2022]['Summons Number'].nunique()
# df['Issue_Year'].unique()

11

#### 2) Identify the vehicles registered in New York (NY) city whose violation code is 40.

In [22]:
df[df['Plate ID'].isna()]

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation,Issue_Year
20627,2000355602,NaN,NY,PAS,07/28/2021,83.0,4DSD,BMW,S,11790,...,NaN,0.0,NaN,0.0,NaN,Improper Registration (NYS Vehicles Only),NaN,NaN,NaN,2021.0
20628,2000355614,NaN,NY,PAS,07/28/2021,74.0,4DSD,ACURA,S,11790,...,NaN,0.0,NaN,0.0,NaN,Missing Plate(s),NaN,NaN,NaN,2021.0
20629,2000355626,NaN,NY,PAS,07/28/2021,83.0,SUBN,FORD,S,11790,...,NaN,0.0,NaN,0.0,NaN,Improper Registration (NYS Vehicles Only),NaN,NaN,NaN,2021.0
20735,2001024976,NaN,99,PAS,07/19/2021,74.0,4DSD,TOYOT,S,24120,...,NaN,0.0,NaN,0.0,NaN,Missing Plate(s),NaN,NaN,NaN,2021.0
28504,2002572835,NaN,99,999,07/22/2021,85.0,TANK,TRACT,S,10390,...,NaN,0.0,NaN,0.0,NaN,Commercial Vehicle Storage 3 Hours,NaN,NaN,NaN,2021.0
32151,2002698533,NaN,99,PAS,07/02/2021,21.0,4DSD,CADIL,S,63120,...,NaN,0.0,NaN,0.0,NaN,No Parking Street Cleaning,NaN,NaN,NaN,2021.0
644581,"""error"" : true",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644582,"""message"" : ""Internal error""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644583,"""status"" : 500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644584,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df[(df['Registration State']=='NY')&(df['Violation Code']==40)]['Plate ID'].nunique()

9543

#### 3) What are the number of states for which tickets have been filed for year 2020? Also

#### provide the list of the states.

#### 4) Count the numbers of vehicles registered in TX for the year 2022.

#### 5) Identify the vehicle involved in parking violations between 2020 to 2022.

#### 6) What are the top 10 most frequently occurring violation codes?

#### 7) Count the number of vehicles whose 'street code1 is â€˜0â€™

#### 8) What are the number of incidents for which address is missing? Consider the Street Codes attributes, i.e. "Street Code 1" or "Street Code 2" or "Street Code 3".

#### 9) What are the top 10 most frequently occurring violation codes?

#### 10)What is the observation with respect to the parking tickets issued based on the vehicle make?

#### 11)Display all the vehicles whose street code1 is â€˜0â€™ and issuing agency is â€˜Pâ€™.

#### 12)Find out the frequencies of tickets raised per season. You can make use of Google search to specify the definition of season.

#### 13)For each of the season identified in (6) above, what are the three most violations.